# Generated by Django 4.0.4 on 2023-03-10 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookshelf',
            old_name='book',
            new_name='books',
        ),
    ]
