# Generated by Django 4.0.4 on 2023-03-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelf',
            name='list_of_books',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='total_books',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_info',
            field=models.JSONField(default=dict),
        ),
    ]
