# Generated by Django 4.0.4 on 2023-03-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_alter_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bookshelf',
        ),
        migrations.AddField(
            model_name='book',
            name='bookshelves',
            field=models.ManyToManyField(related_name='books', to='bookshelf.bookshelf'),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='list_of_books',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='total_books',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
