# Generated by Django 4.0.4 on 2023-03-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_bookshelf_list_of_books_bookshelf_total_books_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bookshelf',
        ),
        migrations.AddField(
            model_name='book',
            name='bookshelf',
            field=models.ManyToManyField(to='bookshelf.bookshelf'),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='list_of_books',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
