# Generated by Django 4.0.4 on 2023-03-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_rename_book_bookshelf_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
