# Generated by Django 4.0.4 on 2023-03-26 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookshelf', '0003_remove_book_bookshelf_book_bookshelves_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookshelves',
            field=models.ManyToManyField(blank=True, related_name='books', to='bookshelf.bookshelf'),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookshelves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='bookshelf',
            name='list_of_books',
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='list_of_books',
            field=models.ManyToManyField(blank=True, related_name='bookContainer', to='bookshelf.book'),
        ),
    ]
